import {
  counterSlice,
  selectCount,
  decrement,
  decrementByAmount,
  increment,
  incrementByAmount,
  square,
  powerOf,
  incrementAsync,
  fetchData,
  incrementIfOdd,
  incrementIfEven,
  reset,
  showAlert,
} from './counterSlice';
import { fetchCount } from './counterAPI';
export {
  counterSlice,
  selectCount,
  decrement,
  decrementByAmount,
  increment,
  incrementByAmount,
  square,
  powerOf,
  incrementAsync,
  fetchData,
  incrementIfOdd,
  incrementIfEven,
  reset,
  showAlert,
  fetchCount,
};
